"""Is this corpus about its subject, or about one project that used it?

WHAT THIS CAUGHT, so nobody deletes it as a nice-to-have. A C# corpus reached
its 1.8M-token quota from 658 files in the first shard. 515 of them imported
`Zynas.Framework.Utility`, 486 wrapped every method in the same trace-log
call, and 82.4% of all lines were repeats. It was one Japanese enterprise
application presented as the C# language.

Nothing downstream could see it. The specialist trained. It diverged from its
neighbour at 263x the chance floor. It won its own domain by 0.43 nats in
cross-domain loss - the strongest routing signal measured on the project - and
reached held-out perplexity 1.33, which reads as a superb expert and actually
means the text was a template. When the collector was fixed and the same
language was gathered from 243 repos instead of 3, that 0.43-nat signal fell
to 0.058. Most of the evidence had been boilerplate.

So this is not a tidiness check. It is the only thing between "we built an
expert" and "we built an expert in one company's house style", and every other
instrument in this package reports the second as the first.

PURE STDLIB, DELIBERATELY. `ms-moe-maker validate` promises to run on a laptop
with no torch, no GPU and no network. A corpus check that cannot run there is
a check that runs after you have already paid for the build.

ADVISORY, NEVER DESTRUCTIVE. Nothing here deletes or rewrites a corpus.
`propose_prune` returns what it WOULD drop and why; writing that out is a
separate, explicitly-asked-for step that produces a NEW file. Same gate as the
consolidator's drafts and the tool registry's proposals - a machine may say
what it thinks should go, and a human commits it.
"""
from __future__ import annotations

import hashlib
import json
import re
from collections import Counter
from dataclasses import dataclass, field
from typing import Any, Dict, Iterator, List, Optional, Tuple

# One repo above this share of the corpus and the expert learns that project,
# not the subject. 25% is generous - the C# failure was at 78%, and a healthy
# 243-repo pull came in at 13%.
REPO_SHARE_WARN = 0.25

# Above this, the text is templated: generated code, boilerplate headers, or
# one project's house style repeated across every file. Measured: 82% on the
# single-repo C# corpus, 57% after the fix, 32% on a diverse Python pull.
LINE_REUSE_WARN = 0.70

# Two documents sharing this many of their first structural lines are the same
# document wearing a different name, for training purposes.
HEADER_LINES = 12

_GENERATED = re.compile(
    r"auto-?generated|<auto-generated|Designer\.cs|AssemblyInfo|"
    r"DO NOT (EDIT|MODIFY)|generated by|swagger|protoc|"
    r"@generated|Code generated by", re.I)


def _rows(path: str, limit: int = 0) -> Iterator[Dict[str, Any]]:
    """Stream a corpus. Never read one whole - see eval.py's OOM arc."""
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for i, line in enumerate(fh):
                if limit and i >= limit:
                    return
                line = line.strip()
                if not line:
                    continue
                try:
                    yield json.loads(line)
                except json.JSONDecodeError:
                    continue
    except OSError:
        return


def _text(row: Dict[str, Any]) -> str:
    return str(row.get("text") or row.get("content") or "")


def _header_sig(text: str) -> str:
    """A signature over a document's opening structural lines.

    Imports, license headers and namespace declarations are what actually
    repeat across one project's files, and they live at the top. Hashing them
    catches "same project, different class" without the cost of shingling the
    whole document.

    LIMITATION, stated rather than discovered: a shared preamble SHORTER than
    HEADER_LINES leaves unique code inside the window, so the signatures
    differ and this metric stays quiet. That case shows up in line reuse
    instead - the two measures cover each other, and neither is sufficient
    alone.
    """
    lines = []
    for line in text.splitlines():
        line = line.strip()
        if line and len(line) > 3:
            lines.append(line)
        if len(lines) >= HEADER_LINES:
            break
    return hashlib.sha1("\n".join(lines).encode("utf-8", "replace")).hexdigest()


@dataclass
class Health:
    path: str = ""
    docs: int = 0
    chars: int = 0
    exact_dupes: int = 0
    line_reuse: float = 0.0
    repos: int = 0
    top_repo: str = ""
    top_repo_share: float = 0.0
    top_header_share: float = 0.0
    generated_markers: int = 0
    has_provenance: bool = False
    findings: List[str] = field(default_factory=list)
    unmeasured: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        d = dict(self.__dict__)
        return d


def inspect(path: str, sample: int = 0, generated: bool = False) -> Health:
    """Measure a corpus file. One pass, bounded memory.

    `generated=True` comes from the Kind registry (synth corpora set it) and
    changes what counts as a finding rather than what gets measured. A corpus
    of tool-call traces is templated ON PURPOSE; warning that it looks
    generated would be the check failing to know what it was pointed at.
    """
    h = Health(path=path)
    seen_docs: set = set()
    headers: Counter = Counter()
    repos: Counter = Counter()
    line_counts: Counter = Counter()
    total_lines = 0

    for row in _rows(path, limit=sample):
        text = _text(row)
        if not text:
            continue
        h.docs += 1
        h.chars += len(text)

        digest = hashlib.sha1(text.encode("utf-8", "replace")).hexdigest()
        if digest in seen_docs:
            h.exact_dupes += 1
        else:
            seen_docs.add(digest)

        headers[_header_sig(text)] += 1
        repo = row.get("repo")
        if repo:
            h.has_provenance = True
            repos[str(repo)] += 1
        if _GENERATED.search(text[:4000]):
            h.generated_markers += 1

        for line in text.splitlines():
            line = line.strip()
            if line:
                total_lines += 1
                line_counts[line] += 1

    if not h.docs:
        h.unmeasured.append(f"no usable rows in {path}")
        return h

    h.line_reuse = 1.0 - (len(line_counts) / max(total_lines, 1))
    if len(repos) > 1:
        name, n = repos.most_common(1)[0]
        h.repos, h.top_repo, h.top_repo_share = len(repos), name, n / h.docs
    elif repos:
        # ONE DISTINCT LABEL CARRIES EXACTLY AS MUCH INFORMATION AS NO LABEL:
        # none. _collect_hf stamps the dataset id, _collect_gh the tarball's
        # top directory and _collect_local the source path - one constant
        # string on every row - so a 5,000-document corpus reported
        # top_repo_share 1.0 and the permanent, unfixable finding "100% of this
        # corpus is one repo, lower corpus.per_repo_cap and re-collect". Then
        # `corpus --prune` believed it and wrote a 20-document corpus. Nothing
        # about repo dominance was measured here; say so instead of 100%.
        h.has_provenance = False
        h.unmeasured.append(
            f"every row carries the same `repo` label "
            f"({repos.most_common(1)[0][0]!r}) - that is what the hf/gh/local "
            f"collectors stamp for a whole source, and it says nothing about "
            f"how many projects are in here. Repo dominance is UNMEASURED, "
            f"not 100%.")
    else:
        h.unmeasured.append(
            "no `repo` field on these rows, so repo dominance cannot be "
            "measured - only line reuse and header repetition. Corpora "
            "collected before provenance stamping look like this.")
    h.top_header_share = headers.most_common(1)[0][1] / h.docs if headers else 0.0

    h.findings = _findings(h, generated=generated)
    return h


def _findings(h: Health, generated: bool = False) -> List[str]:
    out: List[str] = []
    if h.top_repo_share > REPO_SHARE_WARN:
        out.append(
            f"{h.top_repo_share:.0%} of this corpus is one repo ({h.top_repo}). "
            f"The expert will learn that project's house style as if it were "
            f"the subject, and every downstream check will report it as a "
            f"healthy expert. Lower corpus.per_repo_cap and re-collect.")
    if h.exact_dupes:
        out.append(f"{h.exact_dupes} exact duplicate documents "
                   f"({h.exact_dupes / max(h.docs, 1):.1%}).")
    if h.top_header_share > 0.30:
        out.append(
            f"{h.top_header_share:.0%} of documents open with an identical "
            f"{HEADER_LINES}-line header - same imports, same license block, "
            f"or same generated preamble.")

    # A synth corpus is templated BY CONSTRUCTION. Saying "this looks
    # generated" about tool-call traces is the check not knowing what it was
    # pointed at, so the line-reuse finding is suppressed and the fact is
    # reported plainly instead.
    if generated:
        out.append(f"generated corpus: line reuse {h.line_reuse:.0%} is "
                   f"expected for synthesised text and is not a finding.")
    elif h.line_reuse > LINE_REUSE_WARN:
        out.append(
            f"{h.line_reuse:.0%} of lines are repeats - this reads as "
            f"generated or templated code. Expect a very low held-out loss "
            f"that means memorised form, not fluency.")
    if not generated and h.generated_markers > h.docs * 0.15:
        out.append(f"{h.generated_markers} documents "
                   f"({h.generated_markers / max(h.docs, 1):.0%}) carry an "
                   f"auto-generated marker.")
    return out


# ── proposals, not repairs ────────────────────────────────────────────────

@dataclass
class Prune:
    keep: int = 0
    drop: int = 0
    reasons: Counter = field(default_factory=Counter)
    unmeasured: List[str] = field(default_factory=list)


def _distinct_repo_labels(path: str, cap: int = 2) -> int:
    """How many DIFFERENT `repo` values this corpus carries, counted to `cap`.

    One is the same as none - see inspect(). A corpus with real provenance and
    a corpus wearing one constant label look identical to a Counter and are
    completely different claims, and the per-repo cap is only meaningful on the
    first. Stops at `cap`, so the healthy case costs two rows.
    """
    seen: set = set()
    for row in _rows(path):
        r = row.get("repo")
        if r:
            seen.add(str(r))
            if len(seen) >= cap:
                break
    return len(seen)


def propose_prune(path: str, per_repo_cap: int = 20,
                  per_header_cap: int = 20) -> Prune:
    """What WOULD be dropped, and why. Writes nothing.

    Three rules, each one explainable to the person whose data it is:
      * an exact duplicate document is not a second document
      * no repo may contribute more than per_repo_cap
      * no identical header may appear more than per_header_cap times

    Repo dominance is the defect that mattered and it needs the `repo` field.
    On a corpus collected before provenance stamping that rule cannot run,
    and this says so rather than quietly pruning on the two weaker signals
    and reporting success.
    """
    p = Prune()
    seen: set = set()
    repos: Counter = Counter()
    headers: Counter = Counter()
    saw_repo = False
    # A CAP ON A LABEL THAT DOES NOT VARY IS NOT A CAP, IT IS A TRUNCATION.
    # Every hf/gh/local corpus carries one constant `repo`, so this rule would
    # keep the first per_repo_cap documents and drop the rest - 20 kept out of
    # 5,000, below every min_samples floor - on a measurement that never
    # happened. Withhold the rule and report it as unmeasured.
    n_repo_labels = _distinct_repo_labels(path)

    for row in _rows(path):
        text = _text(row)
        if not text:
            p.drop += 1
            p.reasons["empty"] += 1
            continue
        digest = hashlib.sha1(text.encode("utf-8", "replace")).hexdigest()
        if digest in seen:
            p.drop += 1
            p.reasons["exact duplicate"] += 1
            continue
        repo = row.get("repo") if n_repo_labels > 1 else None
        if repo:
            saw_repo = True
            if repos[str(repo)] >= per_repo_cap:
                p.drop += 1
                p.reasons[f"over the {per_repo_cap}/repo cap"] += 1
                continue
        sig = _header_sig(text)
        if headers[sig] >= per_header_cap:
            p.drop += 1
            p.reasons[f"over the {per_header_cap}/identical-header cap"] += 1
            continue

        seen.add(digest)
        if repo:
            repos[str(repo)] += 1
        headers[sig] += 1
        p.keep += 1

    if not saw_repo:
        p.unmeasured.append(
            "no `repo` field on these rows - the per-repo rule could not run, "
            "so repo dominance is NOT addressed by this proposal. Re-collect "
            "with a current build to get provenance stamped."
            if not n_repo_labels else
            "every row carries the same `repo` label - the per-repo rule was "
            "NOT applied, because capping a constant label only truncates the "
            "corpus. Repo dominance is unmeasured here, not fixed.")
    return p


def write_pruned(path: str, out_path: str, per_repo_cap: int = 20,
                 per_header_cap: int = 20) -> Prune:
    """Write the pruned corpus to a NEW file. The original is never touched.

    Deliberately a separate function from propose_prune, called from a
    separate flag, producing a separate file. A person should be able to read
    the proposal, disagree, and have nothing have happened.
    """
    p = Prune()
    seen: set = set()
    repos: Counter = Counter()
    headers: Counter = Counter()
    saw_repo = False
    # A CAP ON A LABEL THAT DOES NOT VARY IS NOT A CAP, IT IS A TRUNCATION.
    # Every hf/gh/local corpus carries one constant `repo`, so this rule would
    # keep the first per_repo_cap documents and drop the rest - 20 kept out of
    # 5,000, below every min_samples floor - on a measurement that never
    # happened. Withhold the rule and report it as unmeasured.
    n_repo_labels = _distinct_repo_labels(path)

    with open(out_path, "w", encoding="utf-8") as fh:
        for row in _rows(path):
            text = _text(row)
            if not text:
                p.drop += 1
                p.reasons["empty"] += 1
                continue
            digest = hashlib.sha1(text.encode("utf-8", "replace")).hexdigest()
            if digest in seen:
                p.drop += 1
                p.reasons["exact duplicate"] += 1
                continue
            repo = row.get("repo") if n_repo_labels > 1 else None
            if repo:
                saw_repo = True
                if repos[str(repo)] >= per_repo_cap:
                    p.drop += 1
                    p.reasons[f"over the {per_repo_cap}/repo cap"] += 1
                    continue
            sig = _header_sig(text)
            if headers[sig] >= per_header_cap:
                p.drop += 1
                p.reasons[f"over the {per_header_cap}/identical-header cap"] += 1
                continue
            seen.add(digest)
            if repo:
                repos[str(repo)] += 1
            headers[sig] += 1
            p.keep += 1
            fh.write(json.dumps(row, ensure_ascii=False) + "\n")

    if not saw_repo:
        p.unmeasured.append(
            "no `repo` field - the per-repo rule did not run"
            if not n_repo_labels else
            "every row carries the same `repo` label - the per-repo rule did "
            "NOT run, because capping a constant label only truncates the "
            "corpus")
    return p


def format_health(h: Health) -> str:
    name = h.path.rsplit("/", 1)[-1]
    lines = [f"  {name}"]
    if not h.docs:
        for u in h.unmeasured:
            lines.append(f"      [?] {u}")
        return "\n".join(lines)
    lines.append(
        f"      {h.docs:,} docs, {h.chars / max(h.docs, 1):,.0f} chars/doc, "
        f"line reuse {h.line_reuse:.0%}, "
        + (f"{h.repos} repos (largest {h.top_repo_share:.1%})"
           if h.has_provenance else "repos unknown"))
    for f in h.findings:
        lines.append(f"      [~] {f}")
    for u in h.unmeasured:
        lines.append(f"      [?] {u}")
    if not h.findings and not h.unmeasured:
        lines.append("      [ok] diverse and unrepetitive")
    return "\n".join(lines)
